---
 - name: Checking inventory hosts
   hosts: all
   connection: local
   gather_facts: false
   tasks:
     - ansible.builtin.debug:
         var: group_names
     - ansible.builtin.debug:
         msg: "{{ inventory_hostname }}"
     - debug:
         var: hostvars[inventory_hostname]

- name: Get node facts for SNOW
  hosts: all
  vars:
    node_info: []
  tasks:
  - name: Collect inventory facts
    ansible.builtin.set_stats:
      data:
        node_info: "{{ node_info + [{'hostname': ansible_facts['nodename'], 'default_ip': ansible_facts['default_ipv4']['address'], 'default_mac': ansible_facts['default_ipv4']['macaddress'], 'vendor': ansible_facts['product_name'] }] }}"
